on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  bump:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - run: |
          sudo apt-get update && sudo apt-get install -y unzip curl jq
      - run: |
          export AUTOBUMP_VERSION=$(curl -sSLH 'Accept: application/vnd.github.v3+json' \
              'https://api.github.com/repos/rios0rios0/autobump/releases/latest' | jq -r '.tag_name')
          curl -LO "https://github.com/rios0rios0/autobump/releases/download/$AUTOBUMP_VERSION/autobump-$AUTOBUMP_VERSION.zip"
          unzip "autobump-$AUTOBUMP_VERSION.zip"
      - run: |
          cat <<-EOF >~/.gitconfig
          [user]
              name = ${{ secrets.GIT_USER }}
              email = ${{ secrets.GIT_USER_EMAIL }}
              signingkey = ${{ secrets.GIT_USER_SIGNINGKEY }}
          [push]
              autoSetupRemote = true
          [commit]
              gpgsign = true
          EOF
      - run: ./autobump batch
